Elimina switch de cambio de theme
ilitteri/Tribu-6-Front-End pull request #36
Opened 2021-12-19 20:50 UTC by sotlucas

2021-12-19 21:27 UTC, ilitteri requested changes, later dismissed
Poner de día

2021-12-19 23:45 UTC, felicoper commented
Esta democracia no funciona

2021-12-19 23:45 UTC, felicoper approved these changes

2021-12-20 01:10 UTC, SBen-IV approved these changes

2021-12-20 01:10 UTC, merged